### ISSUE TITLE
C# - CoreRCON

### ISSUE THREAD

**Issue by Carvalh0XYZ** [ScottKaye/CoreRCON#1]
Hello,
I quickly tried to load the nuget to a "C#" project.
At first, I got 0 conflicts to download and install the package on the C# project.
I've got a conflict when I tried to call the class: new RCON(IPAddress.Parse.....)

It was like a conflict with the IPAddress from System.Net.Primitives. So I updated my .NET Core to see what I could achieve. Now it won't even install the package because the package doesn't have any information for what framework it is...Because it's .NET Core.

My question is, how could I get your awesome library to work on C# ?

Thank you

**Comment by ScottKaye** [comment]
Hi David, glad to see you're interested in CoreRCON!

Can I see your project.json please?

**Comment by Carvalh0XYZ** [comment]
Hello,
It's actually an awesome work ! But would be even good, if I could get it working with C# and do a nice GUI.

Since I installed the update for VS 2015 - Update 3 and installed .NET CORE 1.1 I can't even install the nuget package to any C# Project.

![ss 2017-01-07 at 11 35 06](https://cloud.githubusercontent.com/assets/17826095/21745733/1e0c9c94-d532-11e6-925c-cd21a53a926e.png)

It basically states that it's impossible to install this package on a project for NETFramework 4.5.2, and that the package doesn't contain any file or reference to anything compatible with that infrastrucutre.

Thanks

**Comment by ScottKaye** [comment]
Ah, this is my first package on NuGet, so apologies if it doesn't work straight away!

Could you please try adding `dnxcore50` to your framework imports section under `netcoreapp1.1`?  [Here's an example.](https://github.com/ScottKaye/StatsBot/blob/master/src/StatsBot/project.json#L35)

**Comment by Carvalh0XYZ** [comment]
Your Nuget package works well when I install it on a "C# .NET Core" project. I think, it will not be possible to use it on a "C# Windows Forms" project since it's a different framework.
The Nuget won't install itself on a project that's not targeting .NET Core.

It would be awesome if your project was based from .NET Framework so I could use it with Windows Forms, no big deal tho, I'm gonna try to use "QueryMaster".

Thanks alot for your work !
