### ISSUE TITLE
Connection from same server

### ISSUE THREAD

**Issue by p0457** [ScottKaye/CoreRCON#10]
Got what looks to be a strange situation - I'm running the code for CoreRCON and my Ark server (works with CoreRCON, by the way!), all from the same box. For whatever reason, I cannot get a connection working this way. The same code works from another server, or a local client, but never from the same server that hosts the RCON server and the Ark server.

I tried using local addresses (192.168.1.xxx, 127.0.0.1, localhost, and the public IP address). None work. All of these (with exception to 127.0.0.1 and localhost, for obvious reasons) will work from another device on the network.

Could this be related to CoreRCON and how it handles local requests?

**Comment by ScottKaye** [comment]
I'm a little confused, sorry!  Can you only connect to a server on the same machine with a loopback address, and not the public or NAT IP?  I'm not sure why that would be, but it seems like the workaround is simple enough.

I don't know much about how the networking works at a lower level, unfortunately.  CoreRCON was developed and tested on a local TF2 server connecting to `localhost`, and on a few production TF2 servers connecting to a regular IPv4 address.  It worked for both then - maybe something has changed.

If you're getting any error messages, please let me know!  I don't own ARK and can't really test this.

**Comment by p0457** [comment]
This was not actually related to your code. I am henceforth closing the issue. Sorry about the mistake. CoreRCON is still my favorite RCON client. If you'd like, you can reference that it works perfectly fine for ARK: Survival Evolved!

**Comment by ScottKaye** [comment]
That's great to hear, thanks for following up!  I have added ARK to the known supported games list on the README: db6b775943cce6761dc940ad9b36e4db9b757c3e
