### ISSUE TITLE
Error reading RCON packet from server: Index was out of range.

### ISSUE THREAD

**Issue by MostRush** [ScottKaye/CoreRCON#18]
When i send command trough RCON to my minecraft server it's successfully executed, but answer from server generate error: "Error reading RCON packet from server: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'startIndex')"

Sent command is an plugin's command. And error generated only with any plugin's commands.
With a command of the kernel of minecraft such an error isn't generated.

I know such program as "mcrcon". In this program all plugin's commands successfully return answer.

Perhaps I doing something wrong. Or CoreRcon can't get answer from such commands.

**Comment by ScottKaye** [comment]
There's been quite a few fixes from the new maintainer for this project: https://github.com/Challengermode/CoreRcon Please give it a shot there!
